### ISSUE TITLE
将hexo的math引擎换成mathjax后，编译报错

### ISSUE THREAD

**Issue by HaopengZhang96** [JoeyBling/hexo-theme-yilia-plus#15]
## 按照网上的教程将hexo的引擎换成mathjax后，编译报错。
教程如下：https://www.jianshu.com/p/e8d433a2c5b7

## 🤔结果 & 预期
引擎换成mathjax（kramed替换marked,改变两条转义规则）后，hexo -s g报错：  
SyntaxError: Invalid or unexpected token in "/Users/用户名/hexo/themes/yilia-plus/layout/layout.ejs"
    at new Function (<anonymous>)
    at exports.compile (/Users/用户名/hexo/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:242:14)
    at Object.exports.render (/Users/用户名/hexo/node_modules/hexo-renderer-mathjax/node_modules/ejs/lib/ejs.js:284:66)
    at Hexo.<anonymous> (/Users/用户名/hexo/node_modules/hexo-renderer-mathjax/index.js:14:24)
    at Hexo.tryCatcher (/Users/用户名/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/用户名/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)

ps:换成别的主题没什么问题，可以正常编译和生成，显示数学公式。望解决一下，感谢！！！

## 🐥环境 & 设置

**Node.js & npm version**

 node.js V12.8.1
 npm@6.10.3

**Comment by JoeyBling** [comment]
好像并不需要这么麻烦，直接在主题的`_config.yml`开启```mathjax```即可使用
```yaml
# 数学公式
mathjax: true
```
![](https://user-images.githubusercontent.com/25240064/63560136-707ce180-c587-11e9-944a-46d92208fcd1.png)

**Comment by HaopengZhang96** [comment]
那我明白了，估计是转义两遍崩溃了，早知道我先试试只改mathjax了。谢谢反馈

**Comment by JoeyBling** [comment]
@HaopengZhang96 是的，是直接使用```script```写法直接转义的，你可以查看主题源文件
> layout ➡️  _partial ➡️  mathjax.ejs

**Comment by JoeyBling** [comment]
使用 ```npm uninstall hexo-renderer-mathjax --save``` 卸载掉即可使用
