### ISSUE TITLE
 Process failed: layout/_partial/post/date.ejs

### ISSUE THREAD

**Issue by lijiawang** [JoeyBling/hexo-theme-yilia-plus#31]
## ❓问题
hexo -s css格式错误

    at Theme._View.View.View._precompile (D:\blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\blog\node_modules\graceful-fs\graceful-fs.js:78:16
ERROR Process failed: layout/_partial/tools.ejs
SyntaxError: Invalid or unexpected token in "D:\\blog\\themes\\yilia-plus\\layout\\_partial\\tools.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\blog\node_modules\graceful-fs\graceful-fs.js:78:16
ERROR Process failed: layout/_partial/post/date.ejs
SyntaxError: Invalid or unexpected token in "D:\\blog\\themes\\yilia-plus\\layout\\_partial\\post\\date.ejs"
    at new Function (<anonymous>)
    at Object.exports.compile (D:\blog\node_modules\ejs\lib\ejs.js:242:14)
    at Function.ejsRenderer.compile (D:\blog\node_modules\hexo-renderer-ejs\lib\renderer.js:11:14)
    at Theme._View.View.View._precompile (D:\blog\node_modules\hexo\lib\theme\view.js:119:29)
    at Theme._View.View.View (D:\blog\node_modules\hexo\lib\theme\view.js:13:8)
    at new Theme._View.View (D:\blog\node_modules\hexo\lib\theme\index.js:37:10)
    at Theme.setView (D:\blog\node_modules\hexo\lib\theme\index.js:71:20)
    at D:\blog\node_modules\hexo\lib\theme\processors\view.js:14:14
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\blog\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blog\node_modules\bluebird\js\release\promise.js:638:18)
    at D:\blog\node_modules\bluebird\js\release\nodeback.js:42:21
    at D:\blog\node_modules\graceful-fs\graceful-fs.js:78:16
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.

## 🤔结果 & 预期

Please describe what you expected to see.(请描述一下你希望看到什么)

## 🐥环境 & 设置

**Node.js & npm version**

```bash
```

**Your site `_config.yml`** (Optional)

```yml
```

**Your theme `_config.yml`** (Optional)

```yml
```

**Your browsers** (Optional)

> The browser you use

**Your OSes** (Optional)

> what platforms (operating systems and devices) are affected?

**Comment by yansheng836** [comment]
According to my experience, there will be problems are generally in the modification of the source code, you should go to research is to modify what, before you appear this problem. So may be you need to show us the code what you had changed.

I suggest that you pay special attention to the first problem. From the code you posted, it seems that you can't tell what the problem is.Your title is `Process failed: layout/_partial/post/date.ejs` ,but in you code theres are some problems……

**Comment by JoeyBling** [comment]
你有做主题的二次开发吗?
